export const BASE_URL: string =
  process.env.BASE_URL || 'https://loker-api.vercel.app/api/job';

export const locations: Array<string> = [
  'bali',
  'jakarta',
  'aceh',
  'sumatera-utara',
  'sumatera-barat',
  'riau',
  'kepulauan-riau',
  'jambi',
  'sumatera-selatan',
  'bangka-belitung',
  'bengkulu',
  'lampung',
  'banten',
  'jawa-barat',
  'jawa-timur',
  'jawa-tengah',
  'yogyakarta',
  'nusa-tenggara-barat',
  'nusa-tenggara-timur',
  'kalimantan-barat',
  'kalimantan-tengah',
  'kalimantan-selatan',
  'kalimantan-timur',
  'kalimantan-utara',
  'sulawesi-utara',
  'gorontalo',
  'sulawesi-tengah',
  'sulawesi-barat',
  'sulawesi-selatan',
  'sulawesi-tenggara',
  'maluku',
  'maluku-utara',
  'papua-barat',
  'papua',
];
