name: Awesome loker CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: Install dependencies
        run: npm i -g pnpm && pnpm install --no-frozen-lockfile
      - name: Start update loker data
        run: pnpm start
      - name: Commit and push if it changed
        run: |-
          git config user.name "satyawikananda"
          git config user.email "${{ secrets.EMAIL }}"
          git add -A
          timestamp=$(date -u)
          git commit -m "chore(loker): Update loker" || exit 0
          git push
